from enum import Enum

class KeyCode(Enum):
    KeyCode_A=ord('A')
    KeyCode_B=ord('B')
    KeyCode_C=ord('C')
    KeyCode_D=ord('D')
    KeyCode_E=ord('E')
    KeyCode_F=ord('F')
    KeyCode_G=ord('G')
    KeyCode_H=ord('H')
    KeyCode_I=ord('I')
    KeyCode_J=ord('J')
    KeyCode_K=ord('K')
    KeyCode_L=ord('L')
    KeyCode_M=ord('M')
    KeyCode_N=ord('N')
    KeyCode_O=ord('O')
    KeyCode_P=ord('P')
    KeyCode_Q=ord('Q')
    KeyCode_R=ord('R')
    KeyCode_S=ord('S')
    KeyCode_T=ord('T')
    KeyCode_U=ord('U')
    KeyCode_V=ord('V')
    KeyCode_W=ord('W')
    KeyCode_X=ord('X')
    KeyCode_Y=ord('Y')
    KeyCode_Z=ord('Z')
    KeyCode_0=ord('0')
    KeyCode_1=ord('1')
    KeyCode_2=ord('2')
    KeyCode_3=ord('3')
    KeyCode_4=ord('4')
    KeyCode_5=ord('5')
    KeyCode_6=ord('6')
    KeyCode_7=ord('7')
    KeyCode_8=ord('8')
    KeyCode_9=ord('9')
    KeyCode_Backspace         =8  
    KeyCode_Tab               =9  
    KeyCode_Enter             =13 
    KeyCode_PauseBreak        =19 
    KeyCode_CapsLk            =20 
    KeyCode_Esc               =27 
    KeyCode_Space             =32 
    KeyCode_PageUp            =33 
    KeyCode_PageDown          =34 
    KeyCode_End               =35 
    KeyCode_Home              =36 
    KeyCode_Left              =37 
    KeyCode_Up                =38 
    KeyCode_Right             =39 
    KeyCode_Down              =40 
    KeyCode_PrintScreen       =44 
    KeyCode_Insert            =45 
    KeyCode_Delete            =46 
    KeyCode_LeftWin           =91 
    KeyCode_RightWin          =92 
    KeyCode_Application       =93 
    KeyCode_Multiply          =106# Operator*
    KeyCode_Plus              =107# Operator+
    KeyCode_Minus             =109# Operator-
    KeyCode_Divide            =111# Operator/
    KeyCode_F1                =112
    KeyCode_F2                =113
    KeyCode_F3                =114
    KeyCode_F4                =115
    KeyCode_F5                =116
    KeyCode_F6                =117
    KeyCode_F7                =118
    KeyCode_F8                =119
    KeyCode_F9                =120
    KeyCode_F10               =121
    KeyCode_F11               =122
    KeyCode_F12               =123
    KeyCode_NumLock           =144
    KeyCode_ScrollLock        =145
    KeyCode_LeftShift         =160
    KeyCode_RightShfit        =161
    KeyCode_LeftCtrl          =162
    KeyCode_RightCtrl         =163
    KeyCode_LeftAlt           =164
    KeyCode_RightAlt          =165
    KeyCode_Semicolon         =186# ;
    KeyCode_Equal             =187# =
    KeyCode_Comma             =188# ,
    KeyCode_Hyphen            =189# -
    KeyCode_Period            =190# .
    KeyCode_Slash             =191# /
    KeyCode_BackQuote         =192# `
    KeyCode_LeftSquareBracket =219# [
    KeyCode_VerticalBar       =220# |
    KeyCode_RightSquareBracket=221# ]
    KeyCode_SingleQuote       =222# '
