class KeyCode:
    _A=ord('A')
    _B=ord('B')
    _C=ord('C')
    _D=ord('D')
    _E=ord('E')
    _F=ord('F')
    _G=ord('G')
    _H=ord('H')
    _I=ord('I')
    _J=ord('J')
    _K=ord('K')
    _L=ord('L')
    _M=ord('M')
    _N=ord('N')
    _O=ord('O')
    _P=ord('P')
    _Q=ord('Q')
    _R=ord('R')
    _S=ord('S')
    _T=ord('T')
    _U=ord('U')
    _V=ord('V')
    _W=ord('W')
    _X=ord('X')
    _Y=ord('Y')
    _Z=ord('Z')
    _0=ord('0')
    _1=ord('1')
    _2=ord('2')
    _3=ord('3')
    _4=ord('4')
    _5=ord('5')
    _6=ord('6')
    _7=ord('7')
    _8=ord('8')
    _9=ord('9')
    _Backspace         =8  
    _Tab               =9  
    _Enter             =13 
    _PauseBreak        =19 
    _CapsLk            =20 
    _Esc               =27 
    _Space             =32 
    _PageUp            =33 
    _PageDown          =34 
    _End               =35 
    _Home              =36 
    _Left              =37 
    _Up                =38 
    _Right             =39 
    _Down              =40 
    _PrintScreen       =44 
    _Insert            =45 
    _Delete            =46 
    _LeftWin           =91 
    _RightWin          =92 
    _Application       =93 
    _Multiply          =106# Operator*
    _Plus              =107# Operator+
    _Minus             =109# Operator-
    _Divide            =111# Operator/
    _F1                =112
    _F2                =113
    _F3                =114
    _F4                =115
    _F5                =116
    _F6                =117
    _F7                =118
    _F8                =119
    _F9                =120
    _F10               =121
    _F11               =122
    _F12               =123
    _F13               =124
    _F14               =125
    _F15               =126
    _F16               =127
    _F17               =128
    _F18               =129
    _F19               =130
    _F20               =131
    _NumLock           =144
    _ScrollLock        =145
    _LeftShift         =160
    _RightShfit        =161
    _LeftCtrl          =162
    _RightCtrl         =163
    _LeftAlt           =164
    _RightAlt          =165
    _MediaVolumeMute   =173,
    _MediaVolumeDown   =174,
    _MediaVolumeUp     =175,
    _MediaNextTrack    =176,
    _MediaPrevTrack    =177,
    _MediaStop         =178,
    _MediaPlayPause    =179,
    _Semicolon         =186# ;
    _Equal             =187# =
    _Comma             =188# ,
    _Hyphen            =189# -
    _Period            =190# .
    _Slash             =191# /
    _BackQuote         =192# `
    _LeftSquareBracket =219# [
    _VerticalBar       =220# |
    _RightSquareBracket=221# ]
    _SingleQuote       =222# '